-- MindEase minimal complete development dataset.
-- Intended for an empty counselling_system schema.
-- Passwords are Werkzeug scrypt hashes generated by generate_password_hash().

START TRANSACTION;

INSERT INTO users (UserName, USN, password, role) VALUES
  ('Admin One', 'ADMIN001', 'scrypt:32768:8:1$QOiWwE5U90bmChgc$8326da80468a0f53076691610319e815108ff84e2c6c1b10b5bdbfdb8810a5dbfeb4f1aa45b3a696a5efc9cdd605d235280ab9460ba1de3c7ee133a0899a4289', 'admin'),
  ('Admin Two', 'ADMIN002', 'scrypt:32768:8:1$MwGM4ZorxZSuc2Ht$b18b1ad99ba2cb439e10ac3d1507bed953d63860d5dbf574910623fb38cc2ad6932ba0cca5e50512f41da08c7fe5f38104ee67c2ad524ff1dd527d878059339d', 'admin'),
  ('Admin Three', 'ADMIN003', 'scrypt:32768:8:1$4zzNgwlClc7ntnGv$dc81cdd66be5e4128d7a20bbba748e7297a63c50f0762950934dccdbbb518839e662f6d6698dbbbde1dfd8875ce28158b53a398781735d8dba23d543c7fed895', 'admin'),
  ('Dr Priya Sharma', 'TEACH001', 'scrypt:32768:8:1$yHKSQrS85enbZPcN$06ea2b9ccf3f395db6acdfaad348095f0a7f6b629c2c575f199cb6adb30bb3356642dc503dea6b31fb4effea24e2c03d9578bf9730213a7ed9df734c9fd6bf78', 'teacher'),
  ('Prof Arjun Mehta', 'TEACH002', 'scrypt:32768:8:1$pevqO7cQ3jF6DDll$a51972605ae8a055a2f1beb84c29fc2a028e23161e56186ca7499a295b92622898d7f78d9010eb8bd63cab52e4859a95a6e43431a0a46b1eb8f63e68f9e722e6', 'teacher'),
  ('Ms Neha Rao', 'TEACH003', 'scrypt:32768:8:1$GhWMYPvo9STmmJmq$ce2702c3e1287b8a4009a6a76e6735dd96b157c97db11d242be775e74270a2c13fe0bfdd3356f38a4e822482cfb1dcb86b2185bfec434868fd741c423d723744', 'teacher'),
  ('Aarav Patel', 'STUD001', 'scrypt:32768:8:1$v7x9WbKv3XOuWOLH$9503eafae1b3a4f60fe9485ec4f8d8cc633f704146ed2434d9df5fc75c6460b446670d47b1a4d9cfc8c259724154adeff58253600a2546b3ce97f68def02a7f3', 'student'),
  ('Meera Iyer', 'STUD002', 'scrypt:32768:8:1$zJvCF7VKrYfg945u$5f3f35fa0d0b92075feaa760b6a87fc44cf4dea392e644e5175ebc535919afe91558f6e701b40e71b134b58e9217f50e1594edf4eb0587ad2cd1eda556993b31', 'student'),
  ('Kabir Singh', 'STUD003', 'scrypt:32768:8:1$UVaUps0pFZhISyFI$d0e6939a35c986d95215d59f8d37f9eeb30f18d9d376381bfd9c54872aa852020b0171c0f91794632b3df808d34cb69b395a11cd2aecc909f4b987f58f6ab8cb', 'student');

SET @teacher_one_user = (SELECT id FROM users WHERE USN = 'TEACH001');
SET @teacher_two_user = (SELECT id FROM users WHERE USN = 'TEACH002');
SET @teacher_three_user = (SELECT id FROM users WHERE USN = 'TEACH003');
SET @student_one_user = (SELECT id FROM users WHERE USN = 'STUD001');
SET @student_two_user = (SELECT id FROM users WHERE USN = 'STUD002');
SET @student_three_user = (SELECT id FROM users WHERE USN = 'STUD003');

INSERT INTO teachers (user_id, department, email, designation) VALUES
  (@teacher_one_user, 'Computer Science', 'priya.sharma@example.edu', 'Associate Professor'),
  (@teacher_two_user, 'Electronics', 'arjun.mehta@example.edu', 'Assistant Professor'),
  (@teacher_three_user, 'Mechanical Engineering', 'neha.rao@example.edu', 'Lecturer');

SET @teacher_one = (SELECT id FROM teachers WHERE user_id = @teacher_one_user);
SET @teacher_two = (SELECT id FROM teachers WHERE user_id = @teacher_two_user);
SET @teacher_three = (SELECT id FROM teachers WHERE user_id = @teacher_three_user);

INSERT INTO students (user_id, assigned_teacher_id, department, `class`, email) VALUES
  (@student_one_user, @teacher_one, 'Computer Science', 'BCA 2-A', 'aarav.patel@example.edu'),
  (@student_two_user, @teacher_two, 'Electronics', 'BTech 2-B', 'meera.iyer@example.edu'),
  (@student_three_user, @teacher_three, 'Mechanical Engineering', 'BTech 3-A', 'kabir.singh@example.edu');

SET @student_one = (SELECT id FROM students WHERE user_id = @student_one_user);
SET @student_two = (SELECT id FROM students WHERE user_id = @student_two_user);
SET @student_three = (SELECT id FROM students WHERE user_id = @student_three_user);

-- Gives each student a different teacher-initiated-request state to test.
INSERT INTO teacher_counselling_requests (teacher_id, student_id, reason, message, status) VALUES
  (@teacher_one, @student_one, 'Academic', 'Let us discuss a study plan for the upcoming assessments.', 'Pending'),
  (@teacher_two, @student_two, 'Personal', 'Please book a short follow-up counselling session this week.', 'Accepted'),
  (@teacher_three, @student_three, 'Career', 'I would like to discuss internship preparation options.', 'Rejected');

SET @teacher_request_one = (SELECT id FROM teacher_counselling_requests WHERE teacher_id = @teacher_one AND student_id = @student_one);
SET @teacher_request_two = (SELECT id FROM teacher_counselling_requests WHERE teacher_id = @teacher_two AND student_id = @student_two);

-- One responded/open request, one completed/confidential request, and one pending request.
INSERT INTO counselling_requests (student_id, problem, category, status, is_closed, confidential) VALUES
  (@student_one, 'I am struggling to plan my data structures revision.', 'Academic', 'Teacher Responded', 0, 0);
SET @request_one = LAST_INSERT_ID();

INSERT INTO counselling_requests (student_id, problem, category, status, is_closed, confidential, linked_teacher_request_id) VALUES
  (@student_two, 'I need support balancing family responsibilities and coursework.', 'Personal', 'Completed', 1, 1, @teacher_request_two);
SET @request_two = LAST_INSERT_ID();

INSERT INTO counselling_requests (student_id, problem, category, status, is_closed, confidential) VALUES
  (@student_three, 'I am anxious about the upcoming placement aptitude test.', 'Career', 'Pending', 0, 0);
SET @request_three = LAST_INSERT_ID();

INSERT INTO counselling_messages (request_id, sender_role, message, confidential) VALUES
  (@request_one, 'student', 'I need help creating a realistic weekly revision schedule.', 0),
  (@request_one, 'teacher', 'Start with two focused sessions per day and review progress every Friday.', 0),
  (@request_two, 'student', 'I need a confidential conversation about managing responsibilities at home.', 1),
  (@request_two, 'teacher', 'Thank you for sharing. We can break the workload into manageable steps.', 0),
  (@request_three, 'student', 'I would appreciate tips for preparing calmly for the aptitude test.', 0);

INSERT INTO counselling_responses (request_id, ai_response, teacher_response, completed_at, student_feedback, student_rating) VALUES
  (@request_one, 'Suggested a small, measurable revision plan.', 'Start with two focused sessions per day and review progress every Friday.', NOW(), NULL, NULL),
  (@request_two, NULL, 'Thank you for sharing. We can break the workload into manageable steps.', NOW(), 'The session was supportive and helped me plan the week.', 5);

INSERT INTO student_performance (student_id, subject, marks, attendance_percentage) VALUES
  (@student_one, 'Data Structures', 42, 68),
  (@student_two, 'Digital Electronics', 76, 88),
  (@student_three, 'Thermodynamics', 58, 72);

COMMIT;
